//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entitlement
    {
        public int EN_Id { get; set; }
        public int FK_UG_GroupId { get; set; }
        public string FK_SC_ScreenName { get; set; }
    
        public virtual ScreenName ScreenName { get; set; }
    }
}
