//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMAXV2Entities : DbContext
    {
        public SMAXV2Entities()
            : base("name=SMAXV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Smx_Branch> Smx_Branch { get; set; }
        public virtual DbSet<Smx_CardReissue> Smx_CardReissue { get; set; }
        public virtual DbSet<Smx_CardStatus> Smx_CardStatus { get; set; }
        public virtual DbSet<Smx_Category> Smx_Category { get; set; }
        public virtual DbSet<Smx_Company> Smx_Company { get; set; }
        public virtual DbSet<Smx_EmployeeStatus> Smx_EmployeeStatus { get; set; }
        public virtual DbSet<Smx_Holiday> Smx_Holiday { get; set; }
        public virtual DbSet<Smx_TimeZone> Smx_TimeZone { get; set; }
        public virtual DbSet<Smx_TimeZoneDetails> Smx_TimeZoneDetails { get; set; }
        public virtual DbSet<Smx_Unit> Smx_Unit { get; set; }
        public virtual DbSet<Smx_Designation> Smx_Designation { get; set; }
        public virtual DbSet<Entitlement> Entitlements { get; set; }
        public virtual DbSet<ScreenName> ScreenNames { get; set; }
        public virtual DbSet<Smx_Leave> Smx_Leave { get; set; }
        public virtual DbSet<Smx_Leavedetails> Smx_Leavedetails { get; set; }
        public virtual DbSet<Smx_Areas> Smx_Areas { get; set; }
        public virtual DbSet<vw_AreaName> vw_AreaName { get; set; }
        public virtual DbSet<Smx_Message> Smx_Message { get; set; }
        public virtual DbSet<Smx_Group> Smx_Group { get; set; }
        public virtual DbSet<Smx_Permission> Smx_Permission { get; set; }
        public virtual DbSet<Smx_ShiftAssignment> Smx_ShiftAssignment { get; set; }
        public virtual DbSet<Smx_ShiftAssignmentDetails> Smx_ShiftAssignmentDetails { get; set; }
        public virtual DbSet<Smx_EventTask> Smx_EventTask { get; set; }
        public virtual DbSet<Smx_ShiftDetails> Smx_ShiftDetails { get; set; }
        public virtual DbSet<Smx_Location> Smx_Location { get; set; }
        public virtual DbSet<vw_Smx_AccessLevel_ReaderDetails> vw_Smx_AccessLevel_ReaderDetails { get; set; }
        public virtual DbSet<vw_Smx_CardAccesslevel_Delete> vw_Smx_CardAccesslevel_Delete { get; set; }
        public virtual DbSet<vw_Smx_CardAccesslevel_Download> vw_Smx_CardAccesslevel_Download { get; set; }
        public virtual DbSet<Smx_CardholderAccessLevel> Smx_CardholderAccessLevel { get; set; }
        public virtual DbSet<Smx_AccessLevel> Smx_AccessLevel { get; set; }
        public virtual DbSet<Smx_Transaction> Smx_Transaction { get; set; }
        public virtual DbSet<Smx_TransactionType> Smx_TransactionType { get; set; }
        public virtual DbSet<Smx_AccessLevelDetails> Smx_AccessLevelDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Smx_CardHolder> Smx_CardHolder { get; set; }
        public virtual DbSet<Smx_Department> Smx_Department { get; set; }
        public virtual DbSet<vw_Smx_Transaction> vw_Smx_Transaction { get; set; }
        public virtual DbSet<Smx_Devices> Smx_Devices { get; set; }
        public virtual DbSet<Smx_LastFlashdayscount> Smx_LastFlashdayscount { get; set; }
        public virtual DbSet<Smx_AttendanceReaders> Smx_AttendanceReaders { get; set; }
    
        public virtual int sp_GetAttendenceForMonth(string month, string year)
        {
            var monthParameter = month != null ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetAttendenceForMonth", monthParameter, yearParameter);
        }
    }
}
