//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Company
    {
        public Smx_Company()
        {
            this.Smx_CardHolder = new HashSet<Smx_CardHolder>();
        }
    
        public int CG_ID { get; set; }
        public string CG_NAME { get; set; }
        public string CG_SHORTNAME { get; set; }
        public string CG_HEAD { get; set; }
        public string CG_ADDRESS { get; set; }
        public string CG_CITY { get; set; }
        public string CG_PHONE { get; set; }
        public string CG_FAX { get; set; }
        public string CG_EMAIL { get; set; }
        public System.DateTime CG_CREATED { get; set; }
        public System.DateTime CG_MODIFIED { get; set; }
        public string CG_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_CardHolder> Smx_CardHolder { get; set; }
    }
}
