//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_AccessLevelDetails
    {
        public decimal ALD_ID { get; set; }
        public decimal ALD_AL_ID { get; set; }
        public int ALD_NODEID { get; set; }
        public decimal ALD_TZ_ID { get; set; }
        public string ALD_READER_IPADDRESS { get; set; }
        public int ALD_LN_ID { get; set; }
        public Nullable<System.DateTime> ALD_CREATED { get; set; }
        public Nullable<System.DateTime> ALD_MODIFIED { get; set; }
        public string ALD_MODIFIEDBY { get; set; }
    
        public virtual Smx_AccessLevel Smx_AccessLevel { get; set; }
        public virtual Smx_Location Smx_Location { get; set; }
        public virtual Smx_TimeZone Smx_TimeZone { get; set; }
    }
}
