//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Leave
    {
        public Smx_Leave()
        {
            this.Smx_Leavedetails = new HashSet<Smx_Leavedetails>();
        }
    
        public int Lv_Id { get; set; }
        public string Lv_ShortDesc { get; set; }
        public string Lv_Description { get; set; }
        public Nullable<int> Lv_MaxDays { get; set; }
        public string Lv_MaxAllowed { get; set; }
        public Nullable<System.DateTime> Lv_Created { get; set; }
        public Nullable<System.DateTime> LV_Modified { get; set; }
        public string Lv_Modifiedby { get; set; }
    
        public virtual ICollection<Smx_Leavedetails> Smx_Leavedetails { get; set; }
    }
}
