//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_AttendanceReaders
    {
        public decimal AR_Id { get; set; }
        public string AR_IPAddress { get; set; }
        public Nullable<decimal> AR_Nodeid { get; set; }
        public Nullable<int> AR_ReaderType { get; set; }
        public Nullable<System.DateTime> AR_Createddate { get; set; }
        public string AR_Createdby { get; set; }
        public Nullable<System.DateTime> AR_Modifieddate { get; set; }
        public string AR_Modifiedby { get; set; }
        public string AR_Remarks { get; set; }
    }
}
