//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_ShiftAssignmentDetails
    {
        public decimal Sftd_Id { get; set; }
        public decimal FK_Sft_Id { get; set; }
        public string FK_Emp_Id { get; set; }
        public System.DateTime Sftd_DateTime { get; set; }
    
        public virtual Smx_ShiftDetails Smx_ShiftDetails { get; set; }
    }
}
