//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Permission
    {
        public decimal PR_Id { get; set; }
        public string PR_ChId { get; set; }
        public System.DateTime PR_Date { get; set; }
        public System.DateTime PR_StartTime { get; set; }
        public System.DateTime PR_EndTime { get; set; }
        public Nullable<int> FK_DP_ID { get; set; }
        public string PR_Description { get; set; }
        public string PR_Permission { get; set; }
        public string PR_UpdatedBy { get; set; }
        public Nullable<System.DateTime> PR_CreatedDate { get; set; }
        public Nullable<System.DateTime> PR_ModifiedDate { get; set; }
    }
}
