//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Group
    {
        public decimal PK_Gr_Id { get; set; }
        public string Gr_Name { get; set; }
        public string Gr_ShortName { get; set; }
        public System.DateTime Gr_Created { get; set; }
        public System.DateTime Gr_Modified { get; set; }
        public string Gr_Modifiedby { get; set; }
    }
}
