//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Transaction
    {
        public decimal Tr_Id { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
        public Nullable<System.DateTime> Tr_Time { get; set; }
        public Nullable<decimal> Tr_TType { get; set; }
        public Nullable<decimal> Tr_NodeId { get; set; }
        public Nullable<decimal> Tr_CardNumber { get; set; }
        public string Tr_Csnnumber { get; set; }
        public Nullable<decimal> Tr_Reason { get; set; }
        public string Tr_IpAddress { get; set; }
        public string Tr_Message { get; set; }
        public Nullable<decimal> Tr_TrackCard { get; set; }
        public string Tr_EmpId { get; set; }
        public Nullable<System.DateTime> Tr_Created { get; set; }
    }
}
