//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_ShiftAssignment
    {
        public decimal PK_Sft_Id { get; set; }
        public string Sft_ChId { get; set; }
        public string Sft_MonthYear { get; set; }
        public Nullable<decimal> Sft_D1 { get; set; }
        public Nullable<decimal> Sft_D2 { get; set; }
        public Nullable<decimal> Sft_D3 { get; set; }
        public Nullable<decimal> Sft_D4 { get; set; }
        public Nullable<decimal> Sft_D5 { get; set; }
        public Nullable<decimal> Sft_D6 { get; set; }
        public Nullable<decimal> Sft_D7 { get; set; }
        public Nullable<decimal> Sft_D8 { get; set; }
        public Nullable<decimal> Sft_D9 { get; set; }
        public Nullable<decimal> Sft_D10 { get; set; }
        public Nullable<decimal> Sft_D11 { get; set; }
        public Nullable<decimal> Sft_D12 { get; set; }
        public Nullable<decimal> Sft_D13 { get; set; }
        public Nullable<decimal> Sft_D14 { get; set; }
        public Nullable<decimal> Sft_D15 { get; set; }
        public Nullable<decimal> Sft_D16 { get; set; }
        public Nullable<decimal> Sft_D17 { get; set; }
        public Nullable<decimal> Sft_D18 { get; set; }
        public Nullable<decimal> Sft_D19 { get; set; }
        public Nullable<decimal> Sft_D20 { get; set; }
        public Nullable<decimal> Sft_D21 { get; set; }
        public Nullable<decimal> Sft_D22 { get; set; }
        public Nullable<decimal> Sft_D23 { get; set; }
        public Nullable<decimal> Sft_D24 { get; set; }
        public Nullable<decimal> Sft_D25 { get; set; }
        public Nullable<decimal> Sft_D26 { get; set; }
        public Nullable<decimal> Sft_D27 { get; set; }
        public Nullable<decimal> Sft_D28 { get; set; }
        public Nullable<decimal> Sft_D29 { get; set; }
        public Nullable<decimal> Sft_D30 { get; set; }
        public Nullable<decimal> Sft_D31 { get; set; }
        public Nullable<decimal> Sft_Unit { get; set; }
        public System.DateTime Sft_Created { get; set; }
        public System.DateTime Sft_Modified { get; set; }
        public string Sft_Modifiedby { get; set; }
    }
}
