//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Branch
    {
        public Smx_Branch()
        {
            this.Smx_CardHolder = new HashSet<Smx_CardHolder>();
        }
    
        public int BR_ID { get; set; }
        public string BR_Name { get; set; }
        public Nullable<System.DateTime> BR_CREATED { get; set; }
        public Nullable<System.DateTime> BR_MODIFIED { get; set; }
        public string BR_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_CardHolder> Smx_CardHolder { get; set; }
    }
}
