//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_AccessLevel
    {
        public Smx_AccessLevel()
        {
            this.Smx_CardholderAccessLevel = new HashSet<Smx_CardholderAccessLevel>();
            this.Smx_AccessLevelDetails = new HashSet<Smx_AccessLevelDetails>();
        }
    
        public decimal AL_ID { get; set; }
        public string AL_NAME { get; set; }
        public Nullable<System.DateTime> AL_CREATED { get; set; }
        public Nullable<System.DateTime> AL_MODIFIED { get; set; }
        public string AL_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_CardholderAccessLevel> Smx_CardholderAccessLevel { get; set; }
        public virtual ICollection<Smx_AccessLevelDetails> Smx_AccessLevelDetails { get; set; }
    }
}
