//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Message
    {
        public Smx_Message()
        {
            this.Smx_CardHolder = new HashSet<Smx_CardHolder>();
        }
    
        public int MS_ID { get; set; }
        public string MS_NAME { get; set; }
        public string MS_LINE1 { get; set; }
        public string MS_LINE2 { get; set; }
        public Nullable<System.DateTime> MS_CREATED { get; set; }
        public Nullable<System.DateTime> MS_MODIFIED { get; set; }
        public string MS_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_CardHolder> Smx_CardHolder { get; set; }
    }
}
