//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_CardHolder
    {
        public decimal Ch_Id { get; set; }
        public Nullable<decimal> Ch_Cardno { get; set; }
        public string Ch_Csnnumber { get; set; }
        public string Ch_EmpId { get; set; }
        public string Ch_Title { get; set; }
        public string Ch_FName { get; set; }
        public string Ch_LName { get; set; }
        public string Ch_ShortName { get; set; }
        public Nullable<System.DateTime> Ch_Dob { get; set; }
        public string Ch_Gender { get; set; }
        public string Ch_Nationality { get; set; }
        public string Ch_ContactAddress { get; set; }
        public string Ch_PhoneNumber { get; set; }
        public string Ch_MailId { get; set; }
        public Nullable<int> Ch_Dn_Id { get; set; }
        public Nullable<int> Ch_Ct_Id { get; set; }
        public Nullable<int> Ch_Cg_Id { get; set; }
        public Nullable<int> Ch_Ut_Id { get; set; }
        public Nullable<int> Ch_Br_Id { get; set; }
        public Nullable<int> Ch_Ln_Id { get; set; }
        public Nullable<int> Ch_Dp_Id { get; set; }
        public byte[] Ch_Photo { get; set; }
        public byte[] Ch_Finger1 { get; set; }
        public byte[] Ch_Finger2 { get; set; }
        public Nullable<int> Ch_PinNo { get; set; }
        public Nullable<System.DateTime> Ch_ValidTo { get; set; }
        public Nullable<int> Ch_CS_Id { get; set; }
        public bool Ch_ISBio { get; set; }
        public bool Ch_ISCard { get; set; }
        public bool Ch_ISPin { get; set; }
        public bool Ch_AntiPassBack { get; set; }
        public bool Ch_CardIssued { get; set; }
        public Nullable<bool> Ch_TrackCard { get; set; }
        public Nullable<int> Ch_MS_Id { get; set; }
        public Nullable<System.DateTime> Ch_DOJ { get; set; }
        public Nullable<bool> Ch_AccessValidation { get; set; }
        public Nullable<int> Ch_Es_ID { get; set; }
        public Nullable<System.DateTime> Ch_DOS { get; set; }
        public System.DateTime Ch_Created { get; set; }
        public System.DateTime Ch_Modified { get; set; }
        public string Ch_Modifiedby { get; set; }
        public bool Ch_IsCardBio { get; set; }
        public string Ch_Finger1Identity { get; set; }
        public string Ch_Finger2Identity { get; set; }
        public Nullable<bool> Ch_IsCardBasedBio { get; set; }
    
        public virtual Smx_Branch Smx_Branch { get; set; }
        public virtual Smx_CardStatus Smx_CardStatus { get; set; }
        public virtual Smx_Category Smx_Category { get; set; }
        public virtual Smx_Company Smx_Company { get; set; }
        public virtual Smx_Department Smx_Department { get; set; }
        public virtual Smx_Designation Smx_Designation { get; set; }
        public virtual Smx_EmployeeStatus Smx_EmployeeStatus { get; set; }
        public virtual Smx_Location Smx_Location { get; set; }
        public virtual Smx_Message Smx_Message { get; set; }
        public virtual Smx_Unit Smx_Unit { get; set; }
    }
}
