//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Designation
    {
        public Smx_Designation()
        {
            this.Smx_CardHolder = new HashSet<Smx_CardHolder>();
        }
    
        public int DN_ID { get; set; }
        public string DN_NAME { get; set; }
        public string DN_SHORTNAME { get; set; }
        public Nullable<System.DateTime> DN_CREATED { get; set; }
        public Nullable<System.DateTime> DN_MODIFIED { get; set; }
        public string DN_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_CardHolder> Smx_CardHolder { get; set; }
    }
}
