//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Location
    {
        public Smx_Location()
        {
            this.Smx_Areas = new HashSet<Smx_Areas>();
            this.Smx_AccessLevelDetails = new HashSet<Smx_AccessLevelDetails>();
            this.Smx_CardHolder = new HashSet<Smx_CardHolder>();
            this.Smx_Devices = new HashSet<Smx_Devices>();
        }
    
        public int LN_ID { get; set; }
        public string LN_NAME { get; set; }
        public string LN_ADDRESS { get; set; }
        public string LN_SHORTNAME { get; set; }
        public Nullable<System.DateTime> LN_CREATED { get; set; }
        public Nullable<System.DateTime> LN_MODIFIED { get; set; }
        public string LN_MODIFIEDBY { get; set; }
    
        public virtual ICollection<Smx_Areas> Smx_Areas { get; set; }
        public virtual ICollection<Smx_AccessLevelDetails> Smx_AccessLevelDetails { get; set; }
        public virtual ICollection<Smx_CardHolder> Smx_CardHolder { get; set; }
        public virtual ICollection<Smx_Devices> Smx_Devices { get; set; }
    }
}
