//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_CardReissue
    {
        public decimal CR_ID { get; set; }
        public string CR_Ch_EmpId { get; set; }
        public decimal CR_Ch_CardNo { get; set; }
        public System.DateTime CR_Created { get; set; }
    }
}
