//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Holiday
    {
        public int HD_ID { get; set; }
        public System.DateTime HD_DATE { get; set; }
        public string HD_DESC { get; set; }
        public bool HD_ISREADERDOWNLOAD { get; set; }
        public Nullable<bool> HD_UPDATE_STATUS { get; set; }
        public Nullable<System.DateTime> HD_CREATED { get; set; }
        public Nullable<System.DateTime> HD_MODIFIED { get; set; }
        public string HD_MODIFIEDBY { get; set; }
    }
}
