//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_EventTask
    {
        public decimal ET_ID { get; set; }
        public string ET_Device_IPAddress { get; set; }
        public int ET_NodeId { get; set; }
        public string ET_IP3ACT_R3_Status { get; set; }
        public Nullable<int> ET_IP3ACT_R3_Time { get; set; }
        public Nullable<bool> ET_IP3ACT_R3_Message { get; set; }
        public Nullable<int> ET_IP3ACT_R3_Message_Duration { get; set; }
        public string ET_IP3NRM_R3_Status { get; set; }
        public Nullable<int> ET_IP3NRM_R3_Time { get; set; }
        public Nullable<bool> ET_IP3NRM_R3_Message { get; set; }
        public Nullable<int> ET_IP3NRM_R3_Message_Duration { get; set; }
        public string ET_IP4ACT_R3_Status { get; set; }
        public Nullable<int> ET_IP4ACT_R3_Time { get; set; }
        public Nullable<bool> ET_IP4ACT_R3_Message { get; set; }
        public Nullable<int> ET_IP4ACT_R3_Message_Duration { get; set; }
        public string ET_IP4NRM_R3_Status { get; set; }
        public Nullable<int> ET_IP4NRM_R3_Time { get; set; }
        public Nullable<bool> ET_IP4NRM_R3_Message { get; set; }
        public Nullable<int> ET_IP4NRM_R3_Message_Duration { get; set; }
    }
}
