//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Leavedetails
    {
        public decimal LD_Id { get; set; }
        public Nullable<int> FK_Lv_Id { get; set; }
        public Nullable<System.DateTime> LD_DateLDetails { get; set; }
        public Nullable<decimal> LD_Duration { get; set; }
        public string LD_ChId { get; set; }
        public Nullable<decimal> LD_Unit { get; set; }
        public Nullable<System.DateTime> LD_Created { get; set; }
        public Nullable<System.DateTime> LD_Modified { get; set; }
        public string LD_Modifiedby { get; set; }
    
        public virtual Smx_Leave Smx_Leave { get; set; }
    }
}
