//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_Devices
    {
        public int DE_ID { get; set; }
        public string DE_IPADDRESS { get; set; }
        public int DE_NODEID { get; set; }
        public string DE_NAME { get; set; }
        public int DE_LN_ID { get; set; }
        public string DE_MESSAGE { get; set; }
        public string DE_READERTYPE { get; set; }
        public Nullable<int> DE_RELAYTIME { get; set; }
        public Nullable<int> DE_DOTL { get; set; }
        public Nullable<decimal> DE_DOTZ { get; set; }
        public string DE_IP1_NAME { get; set; }
        public string DE_IP2_NAME { get; set; }
        public string DE_IP1_NONC { get; set; }
        public string DE_IP2_NONC { get; set; }
        public string DE_MEMORY { get; set; }
        public string DE_OPERATIONAL { get; set; }
        public string DE_MODEL { get; set; }
        public string DE_FIRMWARE { get; set; }
        public string DE_READERMODE { get; set; }
        public Nullable<System.DateTime> DE_CREATED { get; set; }
        public Nullable<System.DateTime> DE_MODIFIED { get; set; }
        public string DE_MODIFIEDBY { get; set; }
        public Nullable<int> DE_FIREALARM { get; set; }
        public Nullable<int> DE_INTZID { get; set; }
        public string DE_Remarks { get; set; }
        public Nullable<int> DE_BUZZER_BEEP_COUNT { get; set; }
        public Nullable<int> DE_BUZZER_INTERVAL { get; set; }
        public Nullable<int> DE_OPTIONALTRANS { get; set; }
        public Nullable<int> DE_TIMESYNCTIME { get; set; }
    
        public virtual Smx_Location Smx_Location { get; set; }
    }
}
