//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smx_CardholderAccessLevel
    {
        public decimal CAL_Id { get; set; }
        public Nullable<decimal> CAL_CH_Cardno { get; set; }
        public string CAL_CH_Csnnumber { get; set; }
        public Nullable<decimal> CAL_AL_ID { get; set; }
        public Nullable<bool> CAL_Deleted { get; set; }
        public Nullable<bool> CAL_DWStatus { get; set; }
        public Nullable<System.DateTime> CAL_Created { get; set; }
        public Nullable<System.DateTime> CAL_Modified { get; set; }
        public string CAL_Modifiedby { get; set; }
    
        public virtual Smx_AccessLevel Smx_AccessLevel { get; set; }
    }
}
