//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int US_Id { get; set; }
        public string US_User { get; set; }
        public string US_Login { get; set; }
        public string US_Password { get; set; }
        public int FK_UG_GroupId { get; set; }
        public System.DateTime US_Created { get; set; }
        public System.DateTime US_Modified { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
