//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Smx_AccessLevel_ReaderDetails
    {
        public decimal AL_ID { get; set; }
        public string AL_NAME { get; set; }
        public string DE_NAME { get; set; }
        public decimal ALD_AL_ID { get; set; }
        public int DE_ID { get; set; }
        public string DE_IPADDRESS { get; set; }
        public string ALD_READER_IPADDRESS { get; set; }
    }
}
