//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaxV2Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Smx_Transaction
    {
        public string Emp_Id { get; set; }
        public string Name { get; set; }
        public string Ch_LName { get; set; }
        public string Card_Number { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<decimal> Tr_TType { get; set; }
        public int DE_LN_ID { get; set; }
        public string LN_NAME { get; set; }
        public string Message { get; set; }
        public string Device_Name { get; set; }
        public int DE_ID { get; set; }
    }
}
